#!/bin/bash

#qemu-system-x86_64 -kernel out/vmlinux -nographic -append 'console=ttyS0 rootfstype=tmpfs' -m 1000 -cpu host -enable-kvm

qemu-system-x86_64 -boot d -cdrom out/image.iso -m 1000 -cpu host -enable-kvm -nographic

