#!/bin/bash

mkdir -p out/images/

unlink out/romfs/bin/init
# /bin/init don't work (why?)
cp -f init out/romfs/

cd out/romfs
find . | cpio -o -R root:root -H newc > ../images/initrd.img
cd -

qemu-system-x86_64 -kernel out/images/vmlinux -initrd out/images/initrd.img -nographic -append 'console=ttyS0 debug ignore_loglevel loglevel=8 rootfstype=tmpfs' -m 1000 -cpu host -enable-kvm

